### ISSUE TITLE
accessors for static members

### ISSUE THREAD

**Issue by MWumpusZ** [funkwerk/accessors#16]
Currently this doesn't work with static members:

For a @Read, for example, we get an error like:
src/controller/environment/control/EnvironmentControl.d(49): Error: need 'this' for 'rebootCommand' of type 'inout @property inout(string)()'

If it's easy to fix, it'd be great for this to work; if it's not-so-easy, maybe we can get a better error message in the interim?

**Comment by belka-ew** [comment]
Test case:
```d
class C
{
    @Read
    static int stuff_ = 8;

    mixin(GenerateFieldAccessors);
}

assert(C.stuff == 8);
```
interesting that
```d
assert((new C).stuff == 8));
```
works.

The solution is to make the `@property` static if the corresponding member is static.

**Comment by MWumpusZ** [comment]
> interesting that
> `assert((new C).stuff == 8));`
> works.

Not so surprising though, right?  The error message I get, and your observation, both fit to a (non-static!) read-accessor having been generated.
