### ISSUE TITLE
issue with @nogc @Write function

### ISSUE THREAD

**Issue by linkrope** [funkwerk/accessors#22]
class C
    {
        @Write
        Nullable!SysTime time_;
        mixin(GenerateFieldAccessors);
    }

does not compile:

    Error: @nogc function 'C.time' cannot call non-@nogc generated function 'std.typecons.Nullable!(SysTime).Nullable.opAssign'

**Comment by belka-ew** [comment]
Due to the bug [16206](https://issues.dlang.org/show_bug.cgi?id=16206).
