### ISSUE TITLE
Fails to compile if class uses AliasSeq/Repeat

### ISSUE THREAD

**Issue by mneilly** [funkwerk/accessors#27]
I'm trying to use accessors in a class that has an alias of AliasSeq/Repeat and the compiler fails in accessors.d as follows:

```../../../.dub/packages/accessors-1.2.4/accessors/src/accessors.d-mixin-49(49,15): Error: template std.meta.Alias does not match any template declaration ```

It looks like ```GenerateFieldAccessorMethodsImpl()``` receives ```a``` as a member returned by ```derivedMembers```. I tried making some changes to use ```getSymbolsByUDA``` so that only the attributed members would get returned but have been unsuccessful so far.

The following is minimal example that fails to compile:

```
import accessors;
import std.stdio;
import std.meta : Repeat;

class HyperCube(size_t N_DIM, size_t LEN)
{
  alias a = Repeat!(N_DIM, LEN);
  //alias b = AliasSeq!(LEN, LEN, LEN);

  @Read @Write
  size_t ndim_;

  mixin(GenerateFieldAccessors);
}

void main()
{
  auto grid = new HyperCube!(2, 4);                                                                                                                                                                

  grid.ndim = 2;

  writeln(grid.ndim);
}
```

**Comment by belka-ew** [comment]
accessors aren't actively maintained anymore. Please look into https://github.com/funkwerk/boilerplate and report the bug there if necessary.

**Comment by mneilly** [comment]
Ah, thanks. It does work with boilerplate. :)
